### PR TITLE
GS 45 support

### PR DESCRIPTION
**Pull request by muffinmad**
Solve #62

### CODE REVIEW

**Comment by greatquux** [comment]
did you happen to submit to e.g.o as the version compatible with 45? still seeing the old one there.

**Comment by muffinmad** [comment]
The extension version 45 was rejected. The new [version 46](https://github.com/muffinmad/pidgin-im-gnome-shell-extension/releases/tag/v46) was approved recently. I believe you can find it on e.g.o.

**Comment by greatquux** [comment]
looks like there is a comma that shouldn't be there on line 342. when i remove it, the extension loads and works
Nov 14 22:58:05 ossy gnome-shell[3049294]: JS ERROR: Extension pidgin@muffinmad: SyntaxError: expected property name, got ',' @ file:///home/mike/.local/share/gnome-shell/extensions/pidgin@muffinmad/extension.js:342:2

**Comment by muffinmad** [comment]
Thanks! I've uploaded the new version 47 to e.g.o. and deactivated version 46 as well

**Pull request merged**
